name: blur
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter plugins
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  fluttertoast: ^8.2.12

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2

  # Sign-In providers
  google_sign_in: ^7.1.0
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Blur_Logo_1024x1024.png"
