// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_EaIXI2bqGneIZnaFY7DrvOhVa8vUhic',
    appId: '1:356329679594:ios:78f34e58af06eee5624593',
    messagingSenderId: '356329679594',
    projectId: 'blur-web-app',
    storageBucket: 'blur-web-app.firebasestorage.app',
    androidClientId: '356329679594-avnq3263p644r4qckuml39292n8vuqlu.apps.googleusercontent.com',
    iosClientId: '356329679594-1pbctie0qjkkig9as64vhv5fsn63u1kt.apps.googleusercontent.com',
    iosBundleId: 'com.jadathibodeaux.blur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_EaIXI2bqGneIZnaFY7DrvOhVa8vUhic',
    appId: '1:356329679594:ios:78f34e58af06eee5624593',
    messagingSenderId: '356329679594',
    projectId: 'blur-web-app',
    storageBucket: 'blur-web-app.firebasestorage.app',
    androidClientId: '356329679594-avnq3263p644r4qckuml39292n8vuqlu.apps.googleusercontent.com',
    iosClientId: '356329679594-1pbctie0qjkkig9as64vhv5fsn63u1kt.apps.googleusercontent.com',
    iosBundleId: 'com.jadathibodeaux.blur',
  );
}
